/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
    sepolia: {
        ShadowVault: {
            address: "0x25ba5a7e97e079e1fb7e580e63701fe00ae9ef4e2686e2f4cac0600b1993e34",
            abi: [
                {
                    type: "impl",
                    name: "ShadowVaultImpl",
                    interface_name: "contracts::shadow_vault::IShadowVault",
                },
                {
                    type: "struct",
                    name: "core::integer::u256",
                    members: [
                        {
                            name: "low",
                            type: "core::integer::u128",
                        },
                        {
                            name: "high",
                            type: "core::integer::u128",
                        },
                    ],
                },
                {
                    type: "enum",
                    name: "core::bool",
                    variants: [
                        {
                            name: "False",
                            type: "()",
                        },
                        {
                            name: "True",
                            type: "()",
                        },
                    ],
                },
                {
                    type: "interface",
                    name: "contracts::shadow_vault::IShadowVault",
                    items: [
                        {
                            type: "function",
                            name: "deposit",
                            inputs: [
                                {
                                    name: "amount",
                                    type: "core::integer::u256",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "withdraw",
                            inputs: [
                                {
                                    name: "amount",
                                    type: "core::integer::u256",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "get_balance",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [
                                {
                                    type: "core::integer::u256",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "heartbeat",
                            inputs: [],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "get_last_heartbeat",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [
                                {
                                    type: "core::integer::u64",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "get_heartbeat_interval",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [
                                {
                                    type: "core::integer::u64",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "set_heartbeat_interval",
                            inputs: [
                                {
                                    name: "interval",
                                    type: "core::integer::u64",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "is_dead",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [
                                {
                                    type: "core::bool",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "set_beneficiary",
                            inputs: [
                                {
                                    name: "beneficiary",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                                {
                                    name: "share_bps",
                                    type: "core::integer::u16",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "remove_beneficiary",
                            inputs: [
                                {
                                    name: "beneficiary",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "get_beneficiary_count",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [
                                {
                                    type: "core::integer::u32",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "get_beneficiary_at",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                                {
                                    name: "index",
                                    type: "core::integer::u32",
                                },
                            ],
                            outputs: [
                                {
                                    type: "(core::starknet::contract_address::ContractAddress, core::integer::u16)",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "trigger_distribution",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "set_agent",
                            inputs: [
                                {
                                    name: "agent",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "get_agent",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [
                                {
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "agent_execute",
                            inputs: [
                                {
                                    name: "user",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                                {
                                    name: "amount",
                                    type: "core::integer::u256",
                                },
                                {
                                    name: "recipient",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                    ],
                },
                {
                    type: "impl",
                    name: "OwnableImpl",
                    interface_name: "openzeppelin_access::ownable::interface::IOwnable",
                },
                {
                    type: "interface",
                    name: "openzeppelin_access::ownable::interface::IOwnable",
                    items: [
                        {
                            type: "function",
                            name: "owner",
                            inputs: [],
                            outputs: [
                                {
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            state_mutability: "view",
                        },
                        {
                            type: "function",
                            name: "transfer_ownership",
                            inputs: [
                                {
                                    name: "new_owner",
                                    type: "core::starknet::contract_address::ContractAddress",
                                },
                            ],
                            outputs: [],
                            state_mutability: "external",
                        },
                        {
                            type: "function",
                            name: "renounce_ownership",
                            inputs: [],
                            outputs: [],
                            state_mutability: "external",
                        },
                    ],
                },
                {
                    type: "constructor",
                    name: "constructor",
                    inputs: [
                        {
                            name: "owner",
                            type: "core::starknet::contract_address::ContractAddress",
                        },
                        {
                            name: "token_address",
                            type: "core::starknet::contract_address::ContractAddress",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
                    kind: "struct",
                    members: [
                        {
                            name: "previous_owner",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "new_owner",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
                    kind: "struct",
                    members: [
                        {
                            name: "previous_owner",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "new_owner",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
                    kind: "enum",
                    variants: [
                        {
                            name: "OwnershipTransferred",
                            type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
                            kind: "nested",
                        },
                        {
                            name: "OwnershipTransferStarted",
                            type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
                            kind: "nested",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::DepositMade",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "amount",
                            type: "core::integer::u256",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::WithdrawalMade",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "amount",
                            type: "core::integer::u256",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::HeartbeatRecorded",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "timestamp",
                            type: "core::integer::u64",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::BeneficiarySet",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "beneficiary",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "data",
                        },
                        {
                            name: "share_bps",
                            type: "core::integer::u16",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::BeneficiaryRemoved",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "beneficiary",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::DistributionTriggered",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "total_distributed",
                            type: "core::integer::u256",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::AgentSet",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "agent",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::AgentExecuted",
                    kind: "struct",
                    members: [
                        {
                            name: "user",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "key",
                        },
                        {
                            name: "agent",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "data",
                        },
                        {
                            name: "amount",
                            type: "core::integer::u256",
                            kind: "data",
                        },
                        {
                            name: "recipient",
                            type: "core::starknet::contract_address::ContractAddress",
                            kind: "data",
                        },
                    ],
                },
                {
                    type: "event",
                    name: "contracts::shadow_vault::ShadowVault::Event",
                    kind: "enum",
                    variants: [
                        {
                            name: "OwnableEvent",
                            type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
                            kind: "flat",
                        },
                        {
                            name: "DepositMade",
                            type: "contracts::shadow_vault::ShadowVault::DepositMade",
                            kind: "nested",
                        },
                        {
                            name: "WithdrawalMade",
                            type: "contracts::shadow_vault::ShadowVault::WithdrawalMade",
                            kind: "nested",
                        },
                        {
                            name: "HeartbeatRecorded",
                            type: "contracts::shadow_vault::ShadowVault::HeartbeatRecorded",
                            kind: "nested",
                        },
                        {
                            name: "BeneficiarySet",
                            type: "contracts::shadow_vault::ShadowVault::BeneficiarySet",
                            kind: "nested",
                        },
                        {
                            name: "BeneficiaryRemoved",
                            type: "contracts::shadow_vault::ShadowVault::BeneficiaryRemoved",
                            kind: "nested",
                        },
                        {
                            name: "DistributionTriggered",
                            type: "contracts::shadow_vault::ShadowVault::DistributionTriggered",
                            kind: "nested",
                        },
                        {
                            name: "AgentSet",
                            type: "contracts::shadow_vault::ShadowVault::AgentSet",
                            kind: "nested",
                        },
                        {
                            name: "AgentExecuted",
                            type: "contracts::shadow_vault::ShadowVault::AgentExecuted",
                            kind: "nested",
                        },
                    ],
                },
            ],
            classHash: "0xfdd61d666820cacd36ceed7122bebe0d29ae496c4478f4f4f19bf03459dd45",
        },
    },
} as const;

export default deployedContracts;
